=== morandat/starnet/src/main/resources/fr/labri/timedautomata/ta.xsd
<schema xmlns='http://www.w3.org/2001/XMLSchema' targetNamespace='http://www.w3.org/namespace/' xmlns:t='http://www.w3.org/namespace/'>

 <element name='timedautomata'>
  <complexType>
   <sequence>
    <element ref='t:state' minOccurs='0' maxOccurs='unbounded'/>
   </sequence>
  </complexType>
 </element>

 <element name='state'>
  <complexType>
   <sequence>
    <element ref='t:path' minOccurs='0' maxOccurs='unbounded'/>
    <element ref='t:timeout' minOccurs='0' maxOccurs='1'/>
   </sequence>
   <attribute name='name' type='ID' use='required'/>
   <attribute name='action' type='string' use='optional'/>
   <attribute name='initial' use='optional'>
    <simpleType>
     <restriction base='string'>
      <enumeration value='true'/>
      <enumeration value='false'/>
     </restriction>
    </simpleType>
   </attribute>
	<attribute name='urgent' use='optional'>
	<simpleType>
		<restriction base='string'>
			<enumeration value='true' />
			<enumeration value='false' />
		</restriction>
	</simpleType>
</attribute>
  </complexType>
 </element>

 <element name='path'>
  <complexType>
   <attribute name='to' type='string' use='required'/>
   <attribute name='guard' type='string' use='required'/>
   <attribute name='timeout' type='string' use='optional'/>
  </complexType>
 </element>

 <element name='cron'>
   <sequence>
    <element ref='t:task' minOccurs='0' maxOccurs='unbounded'/>
   </sequence>
 </element>

 <element name='task'>
  <complexType>
   <attribute name='name' type='string' use='optional'/>
   <attribute name='timeout' type='string' use='required'/>
   <attribute name='guard' type='string' use='required'/>
   <attribute name='repeat' type='string' use='optional'/>
   <attribute name='action' type='string' use='required'/>
  </complexType>
 </element>

 <element name='timeout'>
  <complexType>
   <attribute name='to' type='string' use='required'/>
  </complexType>
 </element>
</schema>

=== morandat/starnet/src/main/resources/fr/labri/starnet/policies/GossipPush.xml
<?xml version="1.0" encoding="UTF-8"?>

<timedautomata name="GossipPush"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.labri.fr/~fmoranda/xsd/ta.xsd">

	<state name="init" initial="true" urgent="true" action=BasicActions$InitEnv>
		<path guard="BasicGuards$True" to="mailbox" />
		<spawn name="heart_beat" />
		<spawn name="clean_beat" />
	</state>

	<state name="mailbox" urgent="true" action="BasicActions$SaveMailBox" >
		<path guard="MailBoxGuards$MailBoxIsNotEmpty" to="pop_mailbox" />
		<path guard="BasicGuards$True"  to="wait_next_any_msg" />
	</state>

	<state name="pop_mailbox" urgent="true" >
		<path guard="MailBoxGuards$PopAndIsHelloMsg" to="add_to_hello_set" />
		<path guard="MailBoxGuards$PopAndIsDataMsg" 	to="add_to_data_set" />
		<path guard="BasicGuards$True"  to="wait_next_any_msg" />
	</state>

	<state name="wait_next_any_msg" urgent="false">
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="add_to_hello_set" action="HelloActions$AddToHelloSet"
		urgent="true">
		<path guard="BasicGuards$True" to="pop_mailbox" />
	</state>

	<state name="add_to_data_set" action="DataActions$AddToDataSet"
		urgent="true">
		<path guard="BasicGuards$True" to="broadcast_data_msg" />
	</state>

	<state name="broadcast_data_msg" urgent="true" action="GossipPushActions$DecreaseTTL">
		<path guard="GossipPushGuards$ShouldForwardMsg" to="forward_msg_now" />
		<path guard="BasicGuards$True"  to="pop_mailbox" />
	</state>

	<state name="forward_msg_now" action="GossipPushActions$ForwardMsgToRandomNeighbors"
		urgent="true">
		<path guard="BasicGuards$True" to="pop_mailbox" />
	</state>

	<timedautomata name="heart_beat">
		<state name="init" initial="true">
			<path guard="BasicGuards$False" to="init" timeout="10" />
			<timeout to="send_state" />
		</state>
		<state name="send_state" action="HelloActions$SendHello">
			<path guard="BasicGuards$True" to="init" />
		</state>
	</timedautomata>

	<timedautomata name="clean_beat">
		<state name="init" initial="true">
			<path guard="BasicGuards$False" to="init" timeout="45" />
			<timeout to="clean_state" />
		</state>
		<state name="clean_state" action="HelloActions$CleanHelloSet">
			<path guard="BasicGuards$True" to="init" />
		</state>
	</timedautomata>

</timedautomata>

=== morandat/starnet/src/main/java/fr/labri/starnet/policies/flssk/FLSSk.xml
<?xml version="1.0" encoding="UTF-8"?>

<timedautomata name="FLSSk"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.labri.fr/~fmoranda/xsd/ta.xsd">
	
	<state name="init" initial="true" urgent="true">
		<path guard="BasicGuards$True" to="mailbox" />
		<spawn>
			<automata name="heart_beat" />
			<automata name="process_flss" />
		</spawn>
	</state>
	
	<state name="mailbox" urgent="true">
		<path guard="FLSSKMasterGuards$PopAndIsHelloMsg" to="add_to_hello_set" />
		<path guard="FLSSKMasterGuards$PopAndIsDataMsg" to="msg_broadcast_algo" />
		<path guard="FLSSKMasterGuards$MailBoxEmpty" to="wait_next_any_msg" />
	</state>

	<state name="wait_next_any_msg"  urgent="false">
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="add_to_hello_set" action="FLSSKMasterActions$AddToHelloSet" urgent="true">
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="msg_broadcast_algo" urgent="true">
		<path guard="FLSSKMasterGuards$ShouldForwardMsgNow" to="forward_msg_now" />
		<path guard="FLSSKMasterGuards$ShouldForwardMsgLater" to="forward_msg_later" />
		<path guard="FLSSKMasterGuards$AlreadyReceivedMsg" to="already_received_msg" />
	</state>
	
	<state name="forward_msg_now" action="FLSSKMasterActions$ForwardMsg" urgent="true">
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="forward_msg_later" action="FLSSKMasterActions$SaveMsg" urgent="true">
		<spawn>
			<automata name="forward_msg" />
		</spawn>
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="already_received_msg" urgent="true">
		<path guard="FLSSKMasterGuards$ShouldIgnoreMsg" to="mailbox" />
		<path guard="FLSSKMasterGuards$ShouldNotIgnoreMsg" to="update_neighbors" />
	</state>

	<state name="update_neighbors" action="FLSSKMasterActions$UpdateNeighbors" urgent="true">
		<path guard="FLSSKMasterGuards$NeighborsIsEmpty" to="mailbox" />
		<path guard="FLSSKMasterGuards$NeighborsIsNotEmpty" to="forward_msg_now" />
	</state>
</timedautomata>

<timedautomata name="heart_beat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.labri.fr/~fmoranda/xsd/ta.xsd">
	
	<state name="init" initial="true">
		<path guard="BasicGuards$False" to="init" timeout="10" />
		<timeout to="send_state" />
	</state>
	<state name="send_state" action="HeartBeatActions$SendHello">
		<path guard="BasicGuards$True" to="init" />
	</state>
</timedautomata>

<timedautomata name="process_mst" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.labri.fr/~fmoranda/xsd/ta.xsd">
	<state name="wait_hello_msg" initial="true">
		<path guard="BasicGuards$False" to="init" timeout="10" />
		<timeout to="should_process" />
	</state>
	<state name="should_process">
		<path guard="ProcessMstGuards$AtLeastOneHelloMsg" to="do_process" />
		<path guard="ProcessMstGuards$NoHelloMsg" to="wait_hello_msg" />
	</state>
	<state name="do_process" action="ProcessMstActions$DoProcessAndFlushHelloSet">
		<path guard="BasicGuards$True" to="wait_hello_msg" />
	</state>
</timedautomata>

<timedautomata name="forward_msg">
	<state name="init" initial="true" action="ForwardMsgActions$StoreCurrentMsg">
		<path guard="FLSSKMasterGuards$NeighborsIsEmpty" to="end" timeout="10" />
		<timeout to="forward_now" />
	</state>
	<state name="forward_now" action="ForwardMsgActions$ForwardCurrentStoredMsg">
		<path guard="BasicGuards$True" to="end" />
	</state>
	<state name="end" final="true" />
</timedautomata>

=== morandat/starnet/src/main/resources/fr/labri/starnet/policies/RBOP.xml
<?xml version="1.0" encoding="UTF-8"?>

<timedautomata name="RBOP"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.labri.fr/~fmoranda/xsd/ta.xsd">

	<state name="init" initial="true" urgent="true" >
		<action type="RBOPActions$InitEnv"/>
		<spawn name="heart_beat" />
		<spawn name="process_mst"/>
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="mailbox" urgent="true">
		<action type="BasicActions$SaveMailBox"/>
		<path guard="MailBoxGuards$IsNotEmpty" to="pop_mailbox" />
		<path guard="BasicGuards$True"  to="wait_next_any_msg"  />
	</state>
	
	<state name="pop_mailbox" urgent="true" >
		<path guard="MailBoxGuards$PopAndIsHelloMsg" to="add_to_hello_set" />
		<path guard="MailBoxGuards$PopAndIsDataMsg"  to="add_to_data_set" />
		<path guard="BasicGuards$True"  to="wait_next_any_msg" />
	</state>
	
	<state name="wait_next_any_msg" urgent="false">
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="add_to_data_set" urgent="true">
		<action type="DataActions$AddToDataSet"/>
		<path guard="BasicGuards$True" to="msg_broadcast_algo" />
	</state>

	<state name="add_to_hello_set" urgent="true">
		<action type="HelloActions$AddToHelloSet"/>
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="msg_broadcast_algo" urgent="true">
		<path guard="DataGuards$IsAlreadyReceived" to="already_received_msg" />
		<path guard="BasicGuards$True" to="not_yet_received_msg" />
	</state>
	
	<state name="not_yet_received" urgent="true">
		<path guard="RBOPGuards$IsRngNeighbor" to="forward_msg_now" />
		<path guard="BasicGuards$True" to="forward_msg_later" />
	</state>
	

	<state name="forward_msg_now" urgent="true">
		<action type="DataActions$AddToForwardedSet"/>	
	 	<action type="RBOPActions$ForwardMsg"/>
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="forward_msg_later" urgent="true">
		<action type="RBOPActions$SaveMsg"/>
		<spawn name="forward_msg" />
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="already_received_msg" urgent="true">
		<path guard="DataGuards$IsAlreadyForwarded"  to="mailbox" />
		<path guard="RBOPGuards$NeighborsSetIsEmpty" to="mailbox" />
		<path guard="BasicGuards$True" to="update_neighbors" />
	</state>

	<state name="update_neighbors" urgent="true">
		 <action type="RBOPActions$UpdateNeighbors"/>
		 <path guard="DataGuards$NeighborsSetIsEmpty" to="mailbox" />
		 <path guard="BasicGuards$True" to="forward_msg_now" />
	</state>

	<timedautomata name="heart_beat">
		<state name="init" initial="true">
			<path guard="BasicGuards$False" to="init" timeout="10" />
			<timeout to="send_state" />
		</state>
		<state name="send_state">
		 	<action type="HelloActions$SendHello"/>
			<path guard="BasicGuards$True" to="init" />
		</state>
	</timedautomata>

	<timedautomata name="process_mst">
		<state name="wait_hello_msg" initial="true" urgent="true">
			<path guard="BasicGuards$False" to="init" timeout="10" />
			<timeout to="should_process" />
		</state>
		<state name="should_process" urgent="true">
			<action type="HelloActions$CleanHelloSet"/>
			<path guard="HelloGuards$IsNotEmpty" to="do_process" />
			<path guard="HelloGuards$IsEmpty" to="wait_hello_msg" />
		</state>
		<state name="do_process" urgent="true">
		 	<action type="RBOPActions$DoRngProcess"/>
		 	<action type="HelloActions$CleanHelloSet"/>
			<path guard="BasicGuards$True" to="wait_hello_msg" />
		</state>
	</timedautomata>

	<timedautomata name="forward_msg">
		<state name="init" initial="true" action="????$StoreCurrentMsg">
			<path guard="RBOPGuards$NeighborsSetIsEmpty" to="end"
				timeout="10" />
			<timeout to="forward_now" />
		</state>
		<state name="forward_now" action="???$ForwardCurrentStoredMsg">
			<path guard="BasicGuards$True" to="end" />
		</state>
		<state name="end" action="terminate" />
	</timedautomata>

</timedautomata>

=== morandat/starnet/src/main/java/fr/labri/starnet/policies/pull/GossipPull.xml
<?xml version="1.0" encoding="UTF-8"?>

<timedautomata name="GossipPull"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://www.labri.fr/~fmoranda/xsd/ta.xsd">

	<state name="init" initial="true" urgent="true" action="GossipPullActions$InitEnv">
		<path guard="BasicGuards$True" to="mailbox" />
		<spawn name="heart_beat" />
		<spawn name="clean_beat" />
		<spawn name="probe_beat" />
	</state>

    <state name="mailbox" action="BasicActions$SaveMailBox" urgent="true">
        <path guard="MailBoxGuards$IsNotEmpty" to="pop_mailbox" />
        <path guard="BasicGuards$True"  to="wait_next_any_msg" />
    </state>

	<state name="pop_mailbox" urgent="true">
		<path guard="MailBoxGuards$PopAndIsHelloMsg" to="add_to_hello_set" />
		<path guard="MailBoxGuards$PopAndIsDataMsg" 	to="store_data_msg" />
		<path guard="MailBoxGuards$PopAndIsProbeMsg"	to="send_received_data_msg" />
        <path guard="BasicGuards$True" to="wait_next_any_msg" />
	</state>

	<state name="wait_next_any_msg" urgent="false">
		<path guard="BasicGuards$True" to="mailbox" />
	</state>

	<state name="add_to_hello_set" action="HelloActions$AddToHelloSet"
		urgent="true">
		<path guard="BasicGuards$True" to="pop_mailbox" />
	</state>

	<state name="store_data_msg" urgent="true" action="GossipPullActions$AddToDataSet">
		<path guard="BasicGuards$True" to="pop_mailbox" />
	</state>

	<state name="send_received_data_msg" urgent="true" action="GossipPullActions$SendAndFlushMsgDataSet">
		<path guard="BasicGuards$True" to="pop_mailbox" />
	</state>

	<timedautomata name="heart_beat">
		<state name="init" initial="true">
			<path guard="BasicGuards$False" to="init" timeout="10" />
			<timeout to="send_state" />
		</state>
		<state name="send_state" action="HelloActions$SendHello">
			<path guard="BasicGuards$True" to="init" />
		</state>
	</timedautomata>

	<timedautomata name="clean_beat">
		<state name="init" initial="true">
			<path guard="BasicGuards$False" to="init" timeout="45" />
			<timeout to="clean_state" />
		</state>
		<state name="clean_state" action="HelloActions$CleanHelloSet">
			<path guard="BasicGuards$True" to="init" />
		</state>
	</timedautomata>
	
	<timedautomata name="probe_beat">
		<state name="init" initial="true">
			<path guard="BasicGuards$False" to="init" timeout="45" />
			<timeout to="probe_state" />
		</state>
		<state name="probe_state" action="GossipPullActions$SendProbeToRandomNeighbors">
			<path guard="BasicGuards$True" to="init" />
		</state>
	</timedautomata>
</timedautomata>
